sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t shivamgupta98/learn-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shivamgupta98/learn-docker-react npm run test